### ISSUE TITLE
Add README instructions on how to run tests

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/EC-Chef#16]
Now that we have tests can we get a little bit of a write up on how to run them?

They should be geared towards new contributors. What are the pre-reqs: what sofware needs to be installed, what files need to be created/ what information from the chef server do we need?

After writing them please use a fresh vagrant box and try out the instructions as that is ultimately what I will do (aka Acceptance criteria).

**Comment by anandjainjk** [comment]
Updated README. Verified on a new VM
