### ISSUE TITLE
Update help file for 'all node features'

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/EC-Chef#18]
The help page should have documentation for the new procedures that have been added.
Please also update the Release Notes section

In the PR please cc @jkchew . She will likely have suggestions.

/cc @jkchew

**Comment by anandjainjk** [comment]
We have updated the help file

**Comment by urvashisingh** [comment]
We can close this once the documentation has been reviewed. I have merged the pull request with the images though since it would be easier to review the images in the context of the help file.

**Comment by urvashisingh** [comment]
Anand, 
I noticed that the Release Notes section has not been updated in the help doc for the new procedures that were added. 

-Urvashi

**Comment by urvashisingh** [comment]
Release notes has been updated
