### ISSUE TITLE
Change parameter type for ssh_password parameter in Bootstrap

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/EC-Chef#27]
Use credential parameter instead. We should never ask for a password and store it in clear text.

For the procedure 'Bootstrap' in EC-Chef, the parameter 'ssh_password' is currently 'entry'. 'ssh_password' and 'ssh_user' can be combined into a credential parameter.

This is a blocker and the plugin cannot be shipped unless this is addressed.

**Comment by anandjainjk** [comment]
Implemented
