### ISSUE TITLE
ListRole Procedure should be plural "ListRoles"

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/EC-Chef#32]
There is a discrepancy between what we write in the job output and the name of the name of the procedure. 
 
![plurallistrole](https://cloud.githubusercontent.com/assets/691503/12043835/de2d8244-ae3d-11e5-8dd5-f08a089159dd.PNG)

![singularlistrole](https://cloud.githubusercontent.com/assets/691503/12043836/de2e08c2-ae3d-11e5-8b84-1cbe7209e91f.PNG)

Seeing as we are listing all roles, I vote for changing the procedure name to "ListRoles"

**Comment by chanijindal1** [comment]
For all the list procedures same convention has been used, according to how  knife commands are named.
Fixed the difference for all the procedures.
