### ISSUE TITLE
EditRole Procedure needs adjustment in terms of knife commands called and job step output

### ISSUE THREAD

**Issue by nikhilv** [electric-cloud/EC-Chef#33]
Steps to reproduce

1) Create a role 'test-role1' as follows
```json
{
  "name": "test-role1",
  "description": "foo",
  "json_class": "Chef::Role",
  "default_attributes": {

  },
  "override_attributes": {

  },
  "chef_type": "role",
  "run_list": [

  ],
  "env_run_lists": {

  }
}

```

2) Run the EditRole procedure, change the 'description' in the json above to something like 'foo2'.
![editrole](https://cloud.githubusercontent.com/assets/691503/12044320/1d0634b0-ae44-11e5-9633-dd7c730497c9.PNG)

3) Run procedure

EXPECTED -
Role is edited and job step log reinforces that impression

ACTUAL -
Role is first deleted and then created. Job step output says 'Success: No changes applied' but the description was changed.

Side note: Do we need to issue the delete? From [chef documentation](https://docs.chef.io/knife_role.html) it looks like we only need to issue `knife role from file FILE`

**Comment by anandjainjk** [comment]
We thought delete would make sense so that we do not leave any residue from knife command. Knife by itself is creating a new role/databag/node when the name is edited. Considering this behavior, we have removed the delete from all edit procedures.
