### ISSUE TITLE
Show data bag contents

### ISSUE THREAD

**Issue by anandjainjk** [electric-cloud/EC-Chef#8]

**Comment by nikhilv** [comment]
I'm reviewing the implementation and I have a question. Do we need the `configuration_file` parameter to be required and/or present? It seems like for the other data bag operations this parameter is not present.

Do we need to add this parameter to all other procedures? Or should this parameter be removed?

**Comment by anandjainjk** [comment]
All the common parameters for knife commands have been left out from the procedures. This was an exception which has been fixed.
